// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRHks8NMI1dGFOSrXX022Qp5RbPdpghWY',
    appId: '1:1067925968538:web:431b1565548023dd1f3123',
    messagingSenderId: '1067925968538',
    projectId: 'bot-v1-e524e',
    authDomain: 'bot-v1-e524e.firebaseapp.com',
    databaseURL: 'https://bot-v1-e524e.firebaseio.com',
    storageBucket: 'bot-v1-e524e.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6qSaN_SaBAr5dIzSMprULlubGlIldM5c',
    appId: '1:1067925968538:android:993c55f7a541d3aa1f3123',
    messagingSenderId: '1067925968538',
    projectId: 'bot-v1-e524e',
    databaseURL: 'https://bot-v1-e524e.firebaseio.com',
    storageBucket: 'bot-v1-e524e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBNjQv2hMGgVCKba1oWIn5Mxj3UmnYWTmE',
    appId: '1:1067925968538:ios:125bf069c10c4f821f3123',
    messagingSenderId: '1067925968538',
    projectId: 'bot-v1-e524e',
    databaseURL: 'https://bot-v1-e524e.firebaseio.com',
    storageBucket: 'bot-v1-e524e.appspot.com',
    iosClientId: '1067925968538-9ptlqt06sdt07pbifjev3cdtc770eo4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeNow',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBNjQv2hMGgVCKba1oWIn5Mxj3UmnYWTmE',
    appId: '1:1067925968538:ios:125bf069c10c4f821f3123',
    messagingSenderId: '1067925968538',
    projectId: 'bot-v1-e524e',
    databaseURL: 'https://bot-v1-e524e.firebaseio.com',
    storageBucket: 'bot-v1-e524e.appspot.com',
    iosClientId: '1067925968538-9ptlqt06sdt07pbifjev3cdtc770eo4q.apps.googleusercontent.com',
    iosBundleId: 'com.example.financeNow',
  );
}
